(() => {
  'use strict';
  const client = window.supabaseClient;
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[char]);
  const money = cents => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((cents||0)/100);
  let range = 30;
  let report = null;
  const since = () => { const d=new Date(); d.setDate(d.getDate()-range+1); d.setHours(0,0,0,0); return d.toISOString(); };
  const paidHours = entry => { const end=new Date(entry.clock_out||Date.now()); const breaks=(entry.time_entry_breaks||[]).reduce((sum,b)=>sum+(new Date(b.ended_at||Date.now())-new Date(b.started_at))/3600000,0); return Math.max(0,(end-new Date(entry.clock_in))/3600000-breaks); };

  async function load() {
    const host=document.querySelector('#reports'); if(!host) return;
    const {data:{user}}=await client.auth.getUser(); if(!user) return;
    const {data:profile}=await client.from('profiles').select('*').eq('id',user.id).single(); if(!profile?.active) return;
    const start=since();
    const [repairs,leads,inventory,losses,entries,shifts,comp] = await Promise.all([
      client.from('repair_tickets').select('ticket_number,status,total_cents,subtotal_cents,created_at,updated_at,ready_for_pickup_at,completed_at,assigned_user_id,work_order_items(item_type,description,quantity,unit_cost_cents,unit_price_cents)').eq('location_id',profile.location_id).order('created_at').limit(2000),
      client.from('leads').select('status,source,created_at').eq('location_id',profile.location_id).gte('created_at',start),
      client.from('inventory_items').select('name,sku,quantity_on_hand,reorder_point,cost_cents,sell_price_cents').eq('location_id',profile.location_id),
      client.from('inventory_transactions').select('created_at,quantity_delta,unit_cost_cents,loss_category,loss_amount_cents,recoverable_amount_cents,note,inventory_items(name,sku),profiles:actor_user_id(display_name)').eq('location_id',profile.location_id).eq('transaction_type','write_off').gte('created_at',start).order('created_at',{ascending:false}),
      client.from('time_entries').select('employee_id,clock_in,clock_out,time_entry_breaks(started_at,ended_at)').eq('location_id',profile.location_id).gte('clock_in',start),
      client.from('shifts').select('employee_id,shift_date,starts_at,ends_at,break_minutes').eq('location_id',profile.location_id).gte('shift_date',start.slice(0,10)),
      profile.role==='owner'?client.from('staff_compensation').select('profile_id,hourly_rate_cents').eq('location_id',profile.location_id):Promise.resolve({data:[]})
    ]);
    report={profile,repairs:repairs.data||[],leads:leads.data||[],inventory:inventory.data||[],losses:losses.data||[],entries:entries.data||[],shifts:shifts.data||[],comp:comp.data||[]}; render();
  }

  function render() {
    const host=document.querySelector('#reports'); if(!host||!report)return;
    const completed=report.repairs.filter(r=>['sale_complete','completed'].includes(r.status)&&(r.completed_at||r.created_at)>=since());
    const onShelf=report.repairs.filter(r=>['repaired','ready_for_pickup'].includes(r.status));
    onShelf.forEach(ticket=>{ticket.updated_at=ticket.ready_for_pickup_at||ticket.updated_at;});
    const sales=completed.reduce((s,r)=>s+Number(r.total_cents||0),0);
    const shelfRevenue=onShelf.reduce((s,r)=>s+Number(r.total_cents||0),0);
    const cost=completed.flatMap(r=>r.work_order_items||[]).reduce((s,i)=>s+Number(i.unit_cost_cents||0)*Number(i.quantity||0),0);
    const margin=sales?Math.round((sales-cost)/sales*100):0;
    const won=report.leads.filter(l=>l.status==='won').length;
    const conversion=report.leads.length?Math.round(won/report.leads.length*100):0;
    const actualHours=report.entries.reduce((s,e)=>s+paidHours(e),0);
    const scheduledHours=report.shifts.reduce((s,x)=>{const [a,b]=x.starts_at.split(':').map(Number),[c,d]=x.ends_at.split(':').map(Number);return s+Math.max(0,(c*60+d-a*60-b-x.break_minutes)/60)},0);
    const actualSplh=actualHours?sales/100/actualHours:0;
    const inventoryLoss=report.losses.reduce((sum,item)=>sum+Number(item.loss_amount_cents||0),0);
    const byDay=new Map(); completed.forEach(r=>{const d=(r.completed_at||r.created_at).slice(0,10);byDay.set(d,(byDay.get(d)||0)+Number(r.total_cents||0));});
    const days=[...byDay.entries()].sort((a,b)=>a[0].localeCompare(b[0])); const max=Math.max(1,...days.map(x=>x[1]));
    const lineUsage=new Map(); completed.flatMap(r=>r.work_order_items||[]).forEach(i=>{if(['part','service'].includes(i.item_type))lineUsage.set(i.description,(lineUsage.get(i.description)||0)+Number(i.quantity||0));});
    const top=[...lineUsage.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8);
    const statuses=['new','claimed','qualified','won','lost'].map(status=>[status,report.leads.filter(l=>l.status===status).length]); const maxLead=Math.max(1,...statuses.map(x=>x[1]));
    host.innerHTML=`<div class="page-heading"><div><p class="eyebrow">Live business intelligence</p><h1>Reports & analytics</h1><p class="subtle">Sales, labor, SPLH, leads, inventory, and repair performance from live Portal records.</p></div><div class="quick-actions"><select id="report-range"><option value="7" ${range===7?'selected':''}>Last 7 days</option><option value="30" ${range===30?'selected':''}>Last 30 days</option><option value="90" ${range===90?'selected':''}>Last 90 days</option><option value="365" ${range===365?'selected':''}>Last year</option></select><button class="secondary-button" data-export-report>Export CSV</button><button class="primary-button" data-print-report>Print / PDF</button></div></div>
      <div class="report-metrics"><article class="card"><small>Recognized sales</small><strong>${money(sales)}</strong><span>${completed.length} paid, completed repairs</span></article><article class="card shelf-revenue"><small>Revenue on shelf</small><strong>${money(shelfRevenue)}</strong><span>${onShelf.length} repaired device${onShelf.length===1?'':'s'} awaiting pickup</span></article><article class="card"><small>Gross margin</small><strong>${margin}%</strong><span>${money(sales-cost)} before labor/overhead</span></article><article class="card"><small>Actual SPLH</small><strong>${money(Math.round(actualSplh*100))}</strong><span>${actualHours.toFixed(1)} clocked hours</span></article><article class="card"><small>Inventory loss</small><strong>${money(inventoryLoss)}</strong><span>${report.losses.length} write-offs in range</span></article></div>
      <div class="two-col"><article class="card"><div class="card-title"><div><h2>Sales trend</h2><p>Completed repair revenue by day</p></div></div><div class="bar-chart">${days.map(([date,value])=>`<div class="bar-column" title="${date}: ${money(value)}"><span style="height:${Math.max(3,value/max*100)}%"></span><small>${date.slice(5)}</small></div>`).join('')||'<p class="empty-state">Completed repair sales will appear here.</p>'}</div></article><article class="card"><div class="card-title"><div><h2>Lead pipeline</h2><p>Live conversion funnel</p></div></div><div class="pipeline-chart">${statuses.map(([status,count])=>`<div><label><span>${esc(status)}</span><strong>${count}</strong></label><i><b style="width:${count/maxLead*100}%"></b></i></div>`).join('')}</div></article></div>
      <div class="two-col"><article class="card"><div class="card-title"><div><h2>Labor & productivity</h2><p>Scheduled compared with actual</p></div></div><div class="comparison-bars"><div><label>Scheduled hours <strong>${scheduledHours.toFixed(1)}</strong></label><i><b style="width:${Math.min(100,scheduledHours/Math.max(1,scheduledHours,actualHours)*100)}%"></b></i></div><div><label>Clocked hours <strong>${actualHours.toFixed(1)}</strong></label><i><b style="width:${Math.min(100,actualHours/Math.max(1,scheduledHours,actualHours)*100)}%"></b></i></div></div><div class="settings-list"><label>Sales per labor hour <span>${money(Math.round(actualSplh*100))}</span></label><label>Completed repairs per labor hour <span>${actualHours?(completed.length/actualHours).toFixed(2):'0.00'}</span></label></div></article><article class="card"><div class="card-title"><div><h2>Inventory health</h2><p>Current stock exposure</p></div></div><div class="settings-list"><label>Inventory at cost <span>${money(report.inventory.reduce((s,i)=>s+i.quantity_on_hand*i.cost_cents,0))}</span></label><label>Inventory at retail <span>${money(report.inventory.reduce((s,i)=>s+i.quantity_on_hand*i.sell_price_cents,0))}</span></label><label>Below reorder point <span>${report.inventory.filter(i=>i.quantity_on_hand<=i.reorder_point).length}</span></label></div></article></div>
      <article class="card"><div class="card-title"><div><h2>Revenue on shelf</h2><p>Finished devices still waiting for customer pickup and payment closeout.</p></div><strong>${money(shelfRevenue)}</strong></div><div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Ready since</th><th>Days waiting</th><th>Work-order value</th></tr></thead><tbody>${onShelf.sort((a,b)=>new Date(a.updated_at||a.created_at)-new Date(b.updated_at||b.created_at)).map(ticket=>{const readyDate=ticket.updated_at||ticket.created_at;const age=Math.max(0,Math.floor((Date.now()-new Date(readyDate).getTime())/86400000));return `<tr><td>GC-${String(ticket.ticket_number).padStart(6,'0')}</td><td>${new Date(readyDate).toLocaleDateString()}</td><td>${age}</td><td><strong>${money(ticket.total_cents)}</strong></td></tr>`;}).join('')||'<tr><td colspan="4">No repaired devices are waiting for pickup.</td></tr>'}</tbody></table></div></article><article class="card"><div class="card-title"><div><h2>Top-selling parts & services</h2><p>Quantity used on completed work orders</p></div></div><div class="table-wrap"><table><thead><tr><th>Item</th><th>Quantity</th></tr></thead><tbody>${top.map(([name,quantity])=>`<tr><td>${esc(name)}</td><td>${quantity}</td></tr>`).join('')||'<tr><td colspan="2">No completed work-order line items in this range.</td></tr>'}</tbody></table></div></article><article class="card"><div class="card-title"><div><h2>Inventory loss detail</h2><p>Damage, breakage, shrinkage, obsolescence, and vendor returns.</p></div><strong>${money(inventoryLoss)}</strong></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Item</th><th>Category</th><th>Qty</th><th>Gross cost</th><th>Recovery</th><th>Net loss</th><th>Staff</th></tr></thead><tbody>${report.losses.map(item=>`<tr><td>${new Date(item.created_at).toLocaleDateString()}</td><td>${esc(item.inventory_items?.name||'Inventory item')}<small>${esc(item.note||'')}</small></td><td>${esc(String(item.loss_category||'other').replaceAll('_',' '))}</td><td>${Math.abs(item.quantity_delta)}</td><td>${money(Math.abs(item.quantity_delta)*Number(item.unit_cost_cents||0))}</td><td>${money(item.recoverable_amount_cents)}</td><td>${money(item.loss_amount_cents)}</td><td>${esc(item.profiles?.display_name||'Staff')}</td></tr>`).join('')||'<tr><td colspan="8">No inventory losses in this period.</td></tr>'}</tbody></table></div></article>`;
  }

  function csvEscape(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
  function exportCsv(){if(!report)return;const shelf=report.repairs.filter(r=>['repaired','ready_for_pickup'].includes(r.status));const rows=[['GotCracked report','Value'],['Range (days)',range],['Generated',new Date().toISOString()],['Revenue on shelf',shelf.reduce((sum,r)=>sum+Number(r.total_cents||0),0)/100],[],['Repair ticket','Status','Created','Completed','Total'],...report.repairs.map(r=>[r.ticket_number,r.status,r.created_at,r.completed_at||'',(r.total_cents||0)/100]),[],['Lead status','Source','Created'],...report.leads.map(l=>[l.status,l.source,l.created_at]),[],['Clock in','Clock out','Paid hours'],...report.entries.map(e=>[e.clock_in,e.clock_out||'',paidHours(e).toFixed(2)]),[],['Inventory item','SKU','On hand','Reorder point','Cost','Retail'],...report.inventory.map(i=>[i.name,i.sku,i.quantity_on_hand,i.reorder_point,i.cost_cents/100,i.sell_price_cents/100]),[],['Inventory loss date','Item','SKU','Category','Quantity','Unit cost','Recoverable','Net loss','Note','Reported by'],...report.losses.map(i=>[i.created_at,i.inventory_items?.name||'',i.inventory_items?.sku||'',i.loss_category,Math.abs(i.quantity_delta),(i.unit_cost_cents||0)/100,(i.recoverable_amount_cents||0)/100,(i.loss_amount_cents||0)/100,i.note||'',i.profiles?.display_name||''])];const blob=new Blob([rows.map(row=>row.map(csvEscape).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`GotCracked-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
  document.addEventListener('change',event=>{if(event.target.id==='report-range'){range=Number(event.target.value);load();}});
  document.addEventListener('click',event=>{if(event.target.closest('[data-export-report]'))exportCsv();if(event.target.closest('[data-print-report]'))window.print();});
  document.addEventListener('gc-view-changed',event=>{if(event.detail==='reports')load();});
  client.auth.onAuthStateChange(event=>{if(['SIGNED_IN','INITIAL_SESSION'].includes(event))setTimeout(load,1700);});
  client.channel('report-live').on('postgres_changes',{event:'*',schema:'public',table:'repair_tickets'},()=>setTimeout(load,300)).on('postgres_changes',{event:'*',schema:'public',table:'leads'},()=>setTimeout(load,300)).on('postgres_changes',{event:'*',schema:'public',table:'time_entries'},()=>setTimeout(load,300)).on('postgres_changes',{event:'*',schema:'public',table:'inventory_transactions'},()=>setTimeout(load,300)).subscribe();
})();
