(() => {
  'use strict';
  if (window.GotCrackedDashboardRail) return;
  const client=window.supabaseClient;
  if(!client) return;
  const TZ='America/New_York';
  const state={appointments:[],day:null,timezone:TZ,canManage:false,busy:false,poller:null};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
  const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(c)||0)/100);
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:state.timezone||TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const time=v=>{if(!v)return 'Time TBD';const d=new Date(v);if(!Number.isNaN(d.getTime()))return new Intl.DateTimeFormat('en-US',{timeZone:state.timezone||TZ,hour:'numeric',minute:'2-digit'}).format(d);if(/^\d{2}:\d{2}/.test(String(v))){const [h,m]=String(v).slice(0,5).split(':').map(Number);const x=new Date();x.setHours(h,m,0,0);return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(x)}return String(v)};
  const statusLabel=v=>({requested:'Requested',scheduled:'Scheduled',confirmed:'Confirmed',arrived:'Arrived',completed:'Completed',cancelled:'Cancelled',no_show:'No show'})[v]||String(v||'Scheduled').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
  const statusClass=v=>['confirmed','arrived','completed'].includes(v)?'good':v==='requested'?'warn':'neutral';
  function appointmentStamp(a){if(a.starts_at){const n=new Date(a.starts_at).getTime();if(Number.isFinite(n))return n;}if(a.preferred_time&&/^\d{2}:\d{2}/.test(a.preferred_time)){const [h,m]=a.preferred_time.split(':').map(Number);return h*60+m;}return Number.MAX_SAFE_INTEGER;}
  function renderAppointments(){const host=document.getElementById('gc-dashboard-appointments');if(!host)return;const rows=(state.appointments||[]).filter(a=>!['cancelled','no_show'].includes(String(a.status))).sort((a,b)=>appointmentStamp(a)-appointmentStamp(b));if(!rows.length){host.innerHTML='<div class="gc-rail-empty-state"><span>✓</span><strong>No appointments today</strong><small>The schedule is clear.</small></div>';return;}host.innerHTML=rows.map(a=>{const name=a.customer_name||a.lead_name||'Customer';const device=a.device_description||a.service_requested||'Appointment';const when=a.starts_at?time(a.starts_at):time(a.preferred_time);return `<a class="gc-rail-appointment" href="#appointments" data-view="appointments"><time>${esc(when)}</time><span class="gc-rail-appt-copy"><strong>${esc(name)}</strong><small>${esc(device)}</small></span><b class="gc-rail-status ${statusClass(a.status)}">${esc(statusLabel(a.status))}</b></a>`}).join('');}
  function reconLabel(v){return ({perfect:'Perfect',minor_variance:'Minor variance',needs_review:'Needs review',manager_adjusted:'Manager adjusted',reopened:'Reopened'})[v]||'Reconciled';}
  function renderDay(){const host=document.getElementById('gc-dashboard-day-controls');if(!host)return;const d=state.day||{status:'not_started'};if(d.status==='closed'){host.innerHTML=`<div class="gc-day-head"><div><p class="eyebrow">Business day</p><h3>Day reconciled</h3></div><span class="gc-day-state closed">${esc(reconLabel(d.reconciliation_status))}</span></div><div class="gc-day-meta"><span>Closed ${esc(time(d.closed_at))}</span>${d.goal_cents?`<span>Goal ${money(d.goal_cents)}</span>`:''}</div>${state.canManage?'<button type="button" class="secondary-button gc-day-full" data-gc-day-action="reopen">Reopen day</button>':''}`;return;}if(d.status==='open'){host.innerHTML=`<div class="gc-day-head"><div><p class="eyebrow">Business day</p><h3>Day open</h3></div><span class="gc-day-state open">Live</span></div><div class="gc-day-meta"><span>Started ${esc(time(d.started_at))}</span><span>Opening cash ${money(d.opening_cash_cents)}</span>${d.goal_cents?`<span>Locked goal ${money(d.goal_cents)}</span>`:''}</div>${state.canManage?'<button type="button" class="primary-button gc-day-full" data-gc-day-action="end">End Day & Reconcile</button>':'<p class="gc-day-note">A manager will reconcile and close the business day.</p>'}`;return;}host.innerHTML=`<div class="gc-day-head"><div><p class="eyebrow">Business day</p><h3>Not started</h3></div><span class="gc-day-state">Pending</span></div><p class="gc-day-note">Start Day locks today’s predictive sales goal and records the opening drawer.</p>${state.canManage?'<button type="button" class="primary-button gc-day-full" data-gc-day-action="start">Start Day</button>':'<p class="gc-day-note">Waiting for a manager to start the day.</p>'}`;}
  async function loadPermissions(){try{const {data}=await client.rpc('has_permission',{permission_key:'settings.manage'});state.canManage=Boolean(data);}catch{state.canManage=false;}}
  async function loadAppointments(){const date=today();const {data,error}=await client.rpc('get_appointment_command_center',{range_start:date,range_end:date});if(error)throw error;state.timezone=data?.timezone||state.timezone;state.appointments=Array.isArray(data?.appointments)?data.appointments:[];renderAppointments();}
  async function loadDay(){const {data,error}=await client.rpc('get_business_day_state',{target_date:null});if(error)throw error;state.day=data||null;renderDay();}
  async function load({quiet=false}={}){if(state.busy)return;state.busy=true;try{await loadPermissions();await Promise.all([loadAppointments(),loadDay()]);}catch(error){if(!quiet)window.GotCrackedDiagnostics?.error?.(error,{context:'Dashboard utility rail refresh failed'});console.warn('Dashboard rail refresh failed',error);}finally{state.busy=false;}}
  document.addEventListener('click',event=>{const btn=event.target instanceof Element?event.target.closest('[data-gc-day-action]'):null;if(!btn)return;event.preventDefault();const api=window.GotCrackedSalesOps;const action=btn.dataset.gcDayAction;if(action==='start')api?.openStartDay?.();if(action==='end')api?.openCloseout?.();if(action==='reopen')api?.reopenDay?.();});
  ['gc-sale-completed','gc-cross-user-sync','gc-business-day-change'].forEach(name=>document.addEventListener(name,()=>setTimeout(()=>load({quiet:true}),100)));
  document.addEventListener('gc-portal-runtime-ready',()=>setTimeout(load,80));
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')load({quiet:true});});
  state.poller=setInterval(()=>{if(document.visibilityState==='visible')load({quiet:true});},30000);
  setTimeout(load,500);
  window.GotCrackedDashboardRail={version:'20260827-dashboard-rail2',load,get state(){return state;},stop(){clearInterval(state.poller);}};
})();
