(()=>{
  'use strict';
  if(window.GotCrackedMarlonMonitor)return;
  const buckets=new Map();const created=new Set();const WINDOW_MS=5*60*1000;const THRESHOLD=3;const MAX_BUCKETS=80;
  const clean=v=>String(v?.message||v||'Unknown failure').replace(/\s+/g,' ').trim().slice(0,700);
  const keyFor=(kind,data)=>`${kind}|${clean(data.message||data)}|${data.status||''}|${data.path||location.pathname}`.slice(0,900);
  function profile(){return window.GotCrackedRuntimeProfile||window.GotCrackedOperationsV1?.state?.profile||null}
  function context(extra={}){return{view:location.hash||'#dashboard',path:location.pathname,online:navigator.onLine,runtimeState:document.documentElement.dataset.gcRuntimeState||'',portalBoot:document.documentElement.dataset.gcPortalBoot||'',...extra}}
  async function autoTicket(kind,data,bucket){const support=window.GotCrackedSupportTickets;if(!support?.createAuto||!profile()?.id)return;const signature=keyFor(kind,data);if(created.has(signature))return;created.add(signature);const surface=kind==='website'?'website':'portal';const title=kind==='network'?`Repeated ${data.status||'network'} failure: ${data.path||'Portal request'}`:`Repeated Portal ${kind}: ${clean(data.message||data).slice(0,95)}`;const description=`Marlon observed this behavior ${bucket.times.length} times within five minutes.\n\n${clean(data.message||data)}${data.path?`\nRequest: ${data.method||'GET'} ${data.path}`:''}${data.status?`\nStatus: ${data.status}`:''}\n\nA support ticket was created automatically so the issue can be diagnosed and tracked.`;try{const saved=await support.createAuto({signature,title,description,category:kind==='network'?'workflow':'portal_ui',priority:bucket.times.length>=6?'high':'normal',source:'runtime_error',surface,context:context({kind,count:bucket.times.length,status:data.status||null,requestPath:data.path||null,errorCode:data.code||null,diagnosticId:data.id||null})});if(saved)await createPatchCandidate(saved,title,description,signature)}catch(error){console.warn('Marlon automatic support ticket failed:',error)}}
  async function createPatchCandidate(ticket,title,description,signature){const client=window.supabaseClient;const p=profile();if(!client||!p?.location_id)return;const marker=`marlon-patch:${signature}`;if(sessionStorage.getItem(marker))return;sessionStorage.setItem(marker,'1');try{await client.from('portal_suggestions').insert({location_id:p.location_id,submitted_by:p.id,source:'marlon',surface:'portal',title:`Patch candidate: ${title}`.slice(0,180),description:description.slice(0,5000),category:'reliability',suggestion_type:'patch_candidate',status:'new',owner_review_required:false,marlon_summary:`Automatically correlated with support ticket ${ticket?.ticket_number||''}.`})}catch(error){console.warn('Marlon patch candidate logging failed:',error)}}
  function record(kind,data={}){const key=keyFor(kind,data);const now=Date.now();let b=buckets.get(key);if(!b)b={times:[],last:null};b.times=b.times.filter(t=>now-t<WINDOW_MS);b.times.push(now);b.last=data;buckets.set(key,b);if(buckets.size>MAX_BUCKETS)buckets.delete(buckets.keys().next().value);if(b.times.length===THRESHOLD||b.times.length===6)void autoTicket(kind,data,b)}
  const nativeFetch=window.fetch?.bind(window);if(nativeFetch&&!window.__gcMarlonFetchPatched){window.fetch=async function marlonObservedFetch(input,init){const started=performance.now();try{const response=await nativeFetch(input,init);if(response.status>=400){const url=typeof input==='string'?input:input?.url||'';let path=url;try{const u=new URL(url,location.href);path=u.origin===location.origin?u.pathname:u.hostname+u.pathname}catch{}record('network',{message:`HTTP ${response.status}`,status:response.status,path,method:init?.method||input?.method||'GET',duration:Math.round(performance.now()-started)})}return response}catch(error){const url=typeof input==='string'?input:input?.url||'';let path=url;try{const u=new URL(url,location.href);path=u.origin===location.origin?u.pathname:u.hostname+u.pathname}catch{}record('network',{message:clean(error),status:0,path,method:init?.method||input?.method||'GET',duration:Math.round(performance.now()-started)});throw error}};window.__gcMarlonFetchPatched=true}
  window.addEventListener('error',event=>record('runtime',{message:clean(event.error||event.message),path:location.pathname,stack:String(event.error?.stack||'').slice(0,1200)}));
  window.addEventListener('unhandledrejection',event=>record('promise',{message:clean(event.reason),path:location.pathname,stack:String(event.reason?.stack||'').slice(0,1200)}));
  window.addEventListener('offline',()=>record('connectivity',{message:'Portal browser went offline.',path:location.pathname}));
  document.addEventListener('gc-diagnostic-learning-needed',event=>{const d=event.detail||{};record('diagnostic',{id:d.id||null,code:d.code||null,message:clean(d.message||d.context||'Unclassified Portal error'),path:d.view||d.path||location.pathname,context:d.context||null})});
  const htmlObserver=new MutationObserver(()=>{if(document.documentElement.dataset.gcRuntimeState==='error'||document.documentElement.dataset.gcPortalBoot==='error')record('boot',{message:'Portal runtime entered an error state.',path:location.pathname})});htmlObserver.observe(document.documentElement,{attributes:true,attributeFilter:['data-gc-runtime-state','data-gc-portal-boot']});
  document.addEventListener('gc-view-changed',event=>{const id=typeof event.detail==='string'?event.detail:'';requestAnimationFrame(()=>{if(id&&!document.getElementById(id)?.classList.contains('active-view'))record('workflow',{message:`Navigation did not activate ${id}.`,path:`#${id}`})})});
  document.addEventListener('gc-staff-profile-updated',()=>{setTimeout(()=>{const p=profile();if(p&&!document.getElementById('staff-name')?.textContent?.trim())record('workflow',{message:'Staff identity did not refresh after profile update.',path:'#profile'})},500)});
  window.GotCrackedMarlonMonitor={version:'1.1.0',record,buckets};
})();
