(()=>{
  'use strict';
  if(window.GotCrackedPriceBook)return;
  const client=window.supabaseClient;if(!client)return;
  const state={entries:[],query:'',category:'all',canManage:false,profile:null,loading:false};
  const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(c)||0)/100);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
  const profile=()=>window.GotCrackedRuntimeProfile||window.GotCrackedOperationsV1?.state?.profile||state.profile;
  const parts=e=>Array.isArray(e?.linked_parts)?e.linked_parts:[];
  const directCost=e=>Number(e.cost_cents||0)+parts(e).reduce((sum,p)=>sum+Number(p.unit_cost_cents||0)*Number(p.quantity||1),0);
  const gm=e=>Number(e.price_cents||0)>0?((Number(e.price_cents)-directCost(e))/Number(e.price_cents))*100:null;
  const device=e=>[e.manufacturer,e.model_family,e.device_category].filter(Boolean).join(' · ')||'General service';
  const filtered=()=>state.entries.filter(e=>{
    if(state.category!=='all'&&String(e.category||'Uncategorized')!==state.category)return false;
    const q=state.query.trim().toLowerCase();if(!q)return true;
    return [e.sku,e.name,e.description,e.category,e.device_category,e.manufacturer,e.model_family,...parts(e).flatMap(p=>[p.sku,p.name])].join(' ').toLowerCase().includes(q);
  });
  function latestResearch(e){
    if(e.recommended_price_cents==null)return '<span class="gc-pb-muted">No Marlon market research yet.</span>';
    const range=e.range_low_cents!=null&&e.range_high_cents!=null?`${money(e.range_low_cents)}–${money(e.range_high_cents)}`:'Market range unavailable';
    return `<div class="gc-pb-rec"><strong>${money(e.recommended_price_cents)}</strong><small>${esc(range)}</small>${e.marlon_rationale?`<span>${esc(e.marlon_rationale)}</span>`:''}</div>`;
  }
  function row(e){
    const margin=gm(e),linked=parts(e),actions=[`<button class="secondary-button" type="button" data-pb-copy="${e.id}">Copy quote</button>`];
    if(state.canManage){actions.push(`<button class="secondary-button" type="button" data-pb-edit="${e.id}">Edit</button>`);if(e.price_research_id&&Number(e.recommended_price_cents)!==Number(e.price_cents))actions.push(`<button class="primary-button" type="button" data-pb-apply="${e.price_research_id}">Apply ${money(e.recommended_price_cents)}</button>`);}
    return `<article class="card gc-pb-entry"><div class="gc-pb-entry-head"><div><p class="eyebrow">${esc(e.category||'Service')} · ${esc(e.sku)}</p><h2>${esc(e.name)}</h2><p class="subtle">${esc(device(e))}</p></div><div class="gc-pb-price"><strong>${e.quote_required?'Quote':money(e.price_cents)}</strong><small>${e.estimated_minutes?`${Number(e.estimated_minutes)} min`:'Time varies'}</small></div></div><div class="gc-pb-grid"><div><small>Direct cost</small><strong>${money(directCost(e))}</strong></div><div><small>Est. gross margin</small><strong>${margin==null?'—':`${margin.toFixed(1)}%`}</strong></div><div><small>Common parts</small><strong>${linked.length?linked.map(p=>esc(p.name)).join(', '):'None linked'}</strong></div></div><div class="gc-pb-research"><small>Marlon market guidance</small>${latestResearch(e)}</div>${e.description?`<p class="gc-pb-description">${esc(e.description)}</p>`:''}<div class="gc-pb-actions">${actions.join('')}</div></article>`;
  }
  function render(){
    const host=document.getElementById('price-book');if(!host)return;
    const categories=[...new Set(state.entries.map(e=>String(e.category||'Uncategorized')))].sort();const rows=filtered();
    host.innerHTML=`<div class="page-heading"><div><p class="eyebrow">Fast quoting</p><h1>Price Book</h1><p class="subtle">Customer-facing repair and service pricing, linked to real part cost and Marlon market guidance.</p></div>${state.canManage?'<button class="primary-button" type="button" data-pb-new>+ New Price Book entry</button>':''}</div><div class="card gc-pb-toolbar"><div class="search">⌕ <input data-pb-search placeholder="Search device, repair, service, SKU, or part" value="${esc(state.query)}"></div><select data-pb-category><option value="all">All categories</option>${categories.map(c=>`<option value="${esc(c)}" ${state.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="gc-pb-list">${rows.map(row).join('')||'<div class="empty-card"><h2>No matching Price Book entries.</h2><p>Try another search or add a service.</p></div>'}</div>`;
  }
  async function load(){if(state.loading)return;state.loading=true;try{state.profile=profile();if(!state.profile?.location_id)return;const [inventoryPerm,pricingPerm,data]=await Promise.all([client.rpc('has_permission',{permission_key:'inventory.manage'}),client.rpc('has_permission',{permission_key:'pricing.override'}),client.from('price_book_catalog').select('*').eq('location_id',state.profile.location_id).eq('active',true).order('category').order('name')]);const fallback=['owner','manager'].includes(state.profile.role);const inventoryOk=inventoryPerm.error?fallback:Boolean(inventoryPerm.data),pricingOk=pricingPerm.error?fallback:Boolean(pricingPerm.data);state.canManage=inventoryOk&&pricingOk;if(data.error)throw data.error;state.entries=data.data||[];render();}catch(error){window.GotCrackedDiagnostics?.error?.(error,{context:'Unable to load Price Book'});}finally{state.loading=false;}}

  function ensureDialog(){if(document.getElementById('gc-price-book-dialog'))return;const d=document.createElement('dialog');d.id='gc-price-book-dialog';d.className='gc-pb-dialog';d.innerHTML='<form id="gc-price-book-form" class="gc-pb-dialog-body"></form>';document.body.appendChild(d);}
  function openEditor(entry=null){if(!state.canManage)return;ensureDialog();const f=document.getElementById('gc-price-book-form'),e=entry||{};f.dataset.entryId=e.id||'';f.innerHTML=`<div class="gc-pb-dialog-head"><div><p class="eyebrow">${e.id?'Edit':'New'} Price Book entry</p><h2>${e.id?esc(e.name):'Create service quote'}</h2></div><button class="icon-button" type="button" data-pb-close>×</button></div><div class="v1-form-grid"><label>SKU<input name="sku" required maxlength="80" value="${esc(e.sku||'')}"></label><label>Category<input name="category" maxlength="100" value="${esc(e.category||'Repair')}"></label><label class="full">Service name<input name="name" required maxlength="180" value="${esc(e.name||'')}"></label><label>Device category<input name="device_category" maxlength="80" value="${esc(e.device_category||'')}"></label><label>Manufacturer<input name="manufacturer" maxlength="100" value="${esc(e.manufacturer||'')}"></label><label class="full">Model / family<input name="model_family" maxlength="160" value="${esc(e.model_family||'')}"></label><label>Quote price ($)<input name="price" type="number" min="0" step="0.01" value="${(Number(e.price_cents||0)/100).toFixed(2)}"></label><label>Minimum price ($)<input name="minimum" type="number" min="0" step="0.01" value="${(Number(e.minimum_price_cents||0)/100).toFixed(2)}"></label><label>Estimated minutes<input name="minutes" type="number" min="1" max="1440" value="${e.estimated_minutes||''}"></label><label class="gc-pb-check"><span>Manual quote required</span><input name="quote_required" type="checkbox" ${e.quote_required?'checked':''}></label><label class="full">Description<textarea name="description">${esc(e.description||'')}</textarea></label><label class="full">Pricing notes<textarea name="pricing_notes">${esc(e.pricing_notes||'')}</textarea></label></div><p class="auth-message" role="status"></p><div class="gc-pb-actions"><button class="secondary-button" type="button" data-pb-close>Cancel</button><button class="primary-button" type="submit">Save Price Book entry</button></div>`;document.getElementById('gc-price-book-dialog').showModal();}
  async function save(form){const status=form.querySelector('.auth-message'),fd=new FormData(form),id=form.dataset.entryId||null;const price=Math.round(Number(fd.get('price')||0)*100),minimum=Math.round(Number(fd.get('minimum')||0)*100);if(price<minimum){status.textContent='Quote price cannot be below the configured minimum.';return;}const payload={location_id:state.profile.location_id,sku:String(fd.get('sku')||'').trim(),name:String(fd.get('name')||'').trim(),description:String(fd.get('description')||'').trim()||null,category:String(fd.get('category')||'').trim()||null,price_cents:price,minimum_price_cents:minimum,device_category:String(fd.get('device_category')||'').trim()||null,manufacturer:String(fd.get('manufacturer')||'').trim()||null,model_family:String(fd.get('model_family')||'').trim()||null,estimated_minutes:fd.get('minutes')?Number(fd.get('minutes')):null,quote_required:Boolean(fd.get('quote_required')),pricing_notes:String(fd.get('pricing_notes')||'').trim()||null,price_source:'manual',last_price_review_at:new Date().toISOString(),updated_at:new Date().toISOString()};status.textContent='Saving…';const result=id?await client.from('services').update(payload).eq('id',id).eq('location_id',state.profile.location_id):await client.from('services').insert(payload);if(result.error){status.textContent=result.error.message;return;}document.getElementById('gc-price-book-dialog')?.close();await load();}
  async function applyResearch(id){if(!state.canManage)return;const result=await client.rpc('apply_service_price_recommendation',{p_research_id:id});if(result.error){window.GotCrackedDiagnostics?.error?.(result.error,{context:'Unable to apply Marlon price recommendation'});return;}await load();}
  async function copyQuote(id){const e=state.entries.find(x=>x.id===id);if(!e)return;const text=`${e.name}${device(e)!=='General service'?` (${device(e)})`:''}: ${e.quote_required?'Call for quote':money(e.price_cents)}${e.estimated_minutes?` · approx. ${e.estimated_minutes} min`:''}`;try{await navigator.clipboard.writeText(text);window.GotCrackedDiagnostics?.success?.('Quote copied.');}catch{prompt('Copy quote',text);}}
  document.addEventListener('input',event=>{if(event.target?.matches?.('[data-pb-search]')){state.query=event.target.value;render();}});
  document.addEventListener('change',event=>{if(event.target?.matches?.('[data-pb-category]')){state.category=event.target.value;render();}});
  document.addEventListener('click',event=>{const t=event.target instanceof Element?event.target:null;if(!t)return;if(t.closest('[data-pb-new]'))return openEditor();if(t.closest('[data-pb-close]'))return document.getElementById('gc-price-book-dialog')?.close();const edit=t.closest('[data-pb-edit]');if(edit)return openEditor(state.entries.find(e=>e.id===edit.dataset.pbEdit));const copy=t.closest('[data-pb-copy]');if(copy)return void copyQuote(copy.dataset.pbCopy);const apply=t.closest('[data-pb-apply]');if(apply&&confirm('Apply Marlon’s researched price recommendation to this Price Book entry?'))return void applyResearch(apply.dataset.pbApply);});
  document.addEventListener('submit',event=>{if(event.target?.id!=='gc-price-book-form')return;event.preventDefault();void save(event.target);});
  document.addEventListener('gc-view-changed',event=>{if(event.detail==='price-book')void load();});window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#price-book'))void load();});
  window.GotCrackedPriceBook={version:'1.0.0',state,load};
  ensureDialog();if(location.hash.startsWith('#price-book'))setTimeout(()=>void load(),500);
})();
