(() => {
  'use strict';
  if(window.GotCrackedReconciliationCenter)return;
  const client=window.supabaseClient;if(!client)return;
  const state={data:null,canManage:false,loading:false};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
  const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((Number(c)||0)/100);
  const date=v=>{if(!v)return '—';const d=new Date(`${String(v).slice(0,10)}T12:00:00`);return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d)};
  const statusLabel=v=>({perfect:'Perfect',minor_variance:'Minor variance',needs_review:'Needs review',manager_adjusted:'Manager adjusted',reopened:'Reopened'})[v]||String(v||'Pending').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
  const statusClass=v=>({perfect:'good',minor_variance:'warn',needs_review:'bad',manager_adjusted:'adjusted',reopened:'reopened'})[v]||'neutral';
  async function permissions(){try{const {data}=await client.rpc('has_permission',{permission_key:'settings.manage'});state.canManage=Boolean(data);}catch{state.canManage=false;}}
  function ensureHost(){const reports=document.getElementById('reports');if(!reports)return null;let host=document.getElementById('gc-reconciliation-center');if(!host){host=document.createElement('section');host.id='gc-reconciliation-center';host.className='gc-reconciliation-center';reports.appendChild(host);}return host;}
  function totals(rows){return rows.reduce((a,r)=>{a.total+=Number(r.reconciled_total_sales_cents||0);a.external+=Number(r.pos_net_sales_cents||0);a.internal+=Number(r.portal_internal_sales_cents||0);a.absVariance+=Math.abs(Number(r.portal_pos_variance_cents||0));a.closed+=r.status==='closed'?1:0;return a;},{total:0,external:0,internal:0,absVariance:0,closed:0});}
  function render(){const host=ensureHost();if(!host)return;const rows=Array.isArray(state.data?.rows)?state.data.rows:[],t=totals(rows);host.innerHTML=`<div class="gc-recon-title"><div><p class="eyebrow">Finance operations</p><h2>Reconciliation Center</h2><p>External POS printouts are reconciled against Portal-expected external sales. Direct/internal revenue is then added for the true shop total.</p></div><button type="button" class="secondary-button" data-gc-recon-export ${rows.length?'':'disabled'}>Export CSV</button></div><div class="gc-recon-metrics"><article><small>Reconciled sales</small><strong>${money(t.total)}</strong><span>${t.closed} closed day${t.closed===1?'':'s'}</span></article><article><small>External POS</small><strong>${money(t.external)}</strong><span>Printed net sales</span></article><article><small>Direct / internal</small><strong>${money(t.internal)}</strong><span>Portal-ledger revenue</span></article><article><small>Absolute POS variance</small><strong>${money(t.absVariance)}</strong><span>Across selected period</span></article></div>${rows.length?`<div class="gc-recon-table-wrap"><table class="gc-recon-table"><thead><tr><th>Date</th><th>Status</th><th>Goal</th><th>External expected</th><th>POS printed</th><th>Variance</th><th>Direct</th><th>Total</th><th>Drawer</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(date(r.business_date))}</strong><small>${esc(r.pos_reference||'No POS ref')}</small></td><td><span class="gc-recon-badge ${statusClass(r.reconciliation_status)}">${esc(statusLabel(r.reconciliation_status))}</span></td><td>${money(r.goal_cents)}</td><td>${money(r.portal_external_expected_cents)}</td><td>${money(r.pos_net_sales_cents)}</td><td class="${Number(r.portal_pos_variance_cents||0)?'gc-recon-variance':''}">${money(r.portal_pos_variance_cents)}</td><td>${money(r.portal_internal_sales_cents)}</td><td><strong>${money(r.reconciled_total_sales_cents)}</strong></td><td class="${Number(r.cash_over_short_cents||0)?'gc-recon-variance':''}">${money(r.cash_over_short_cents)}</td><td>${state.canManage&&r.status==='closed'?`<button class="text-button" type="button" data-gc-recon-reopen="${esc(r.business_date)}">Reopen</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="gc-recon-empty"><span>◎</span><h3>No reconciled days yet</h3><p>The first End Day closeout will appear here with external POS variance, direct revenue, drawer variance, and the final daily total.</p></div>'}`;}
  async function load(){if(state.loading)return;state.loading=true;const host=ensureHost();if(host&&!state.data)host.innerHTML='<div class="card gc-recon-loading">Loading reconciliation history…</div>';try{await permissions();const {data,error}=await client.rpc('get_reconciliation_history',{range_start:null,range_end:null});if(error)throw error;state.data=data||{rows:[]};render();}catch(error){if(host)host.innerHTML=`<div class="card gc-recon-error">${esc(error?.message||'Unable to load reconciliation history.')}</div>`;console.warn(error);}finally{state.loading=false;}}
  function exportCsv(){const rows=state.data?.rows||[];if(!rows.length)return;const cols=[['Date','business_date'],['Status','reconciliation_status'],['Goal','goal_cents'],['Portal External Expected','portal_external_expected_cents'],['POS Net','pos_net_sales_cents'],['External Variance','portal_pos_variance_cents'],['Direct/Internal','portal_internal_sales_cents'],['Reconciled Total','reconciled_total_sales_cents'],['Cash Over/Short','cash_over_short_cents'],['Tender Variance','tender_variance_cents'],['Transactions','transaction_count'],['POS Reference','pos_reference'],['Notes','notes']];const q=v=>`"${String(v??'').replaceAll('"','""')}"`;const text=[cols.map(x=>q(x[0])).join(','),...rows.map(r=>cols.map(([,k])=>q(r[k])).join(','))].join('\n');const blob=new Blob([text],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gotcracked-reconciliation-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  document.addEventListener('click',async event=>{const t=event.target instanceof Element?event.target:null;if(!t)return;if(t.closest('[data-gc-recon-export]'))return exportCsv();const reopen=t.closest('[data-gc-recon-reopen]');if(reopen){event.preventDefault();await window.GotCrackedSalesOps?.reopenDay?.(reopen.dataset.gcReconReopen);await load();return;}const view=t.closest('[data-view]')?.dataset.view;if(view==='reports')setTimeout(load,160);});
  document.addEventListener('gc-business-day-change',()=>setTimeout(load,150));
  if(location.hash.startsWith('#reports'))setTimeout(load,700);
  window.GotCrackedReconciliationCenter={version:'20260827-reconciliation2',load,render};
})();
