(()=>{
  'use strict';
  if(window.GotCrackedWorkstationAdmin)return;
  const client=window.supabaseClient;if(!client)return;
  const profile=()=>window.GotCrackedRuntimeProfile||window.GotCrackedOperationsV1?.state?.profile||null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let rows=[];
  async function rpc(name,args={}){const{data,error}=await client.rpc(name,args);if(error)throw error;return data;}
  function style(){if(document.getElementById('gc-workstation-admin-style'))return;const s=document.createElement('style');s.id='gc-workstation-admin-style';s.textContent='.gc-workstation-admin{margin-top:16px}.gc-workstation-admin-list{display:grid;gap:9px;margin-top:14px}.gc-workstation-admin-row{display:grid;grid-template-columns:minmax(180px,1.2fr) minmax(160px,1fr) auto;gap:12px;align-items:center;padding:13px;border:1px solid rgba(123,151,181,.17);border-radius:13px}.gc-workstation-admin-row small{display:block;opacity:.7;margin-top:3px}.gc-trust-pill{display:inline-flex;width:max-content;padding:4px 8px;border-radius:999px;background:rgba(35,151,103,.12);font-size:10px;font-weight:850;text-transform:uppercase}.gc-trust-pill.revoked{background:rgba(123,151,181,.12)}@media(max-width:680px){.gc-workstation-admin-row{grid-template-columns:1fr auto}.gc-workstation-admin-row>div:nth-child(2){grid-column:1/-1}}';document.head.appendChild(s);}
  function eligible(){const p=profile();return p?.account_type!=='shared_workstation'&&['owner','manager'].includes(p?.role);}
  function ensure(){const settings=document.getElementById('settings');if(!settings||!eligible())return null;let host=document.getElementById('gc-workstation-admin');if(host)return host;host=document.createElement('section');host.id='gc-workstation-admin';host.className='card gc-workstation-admin';const heading=settings.querySelector('.page-heading');heading?.insertAdjacentElement('afterend',host);return host;}
  function render(){const host=ensure();if(!host)return;const active=rows.filter(x=>!x.revoked_at);const history=rows.filter(x=>x.revoked_at).slice(0,4);const markup=[...active,...history].map(row=>`<div class="gc-workstation-admin-row"><div><strong>${esc(row.device_label||row.workstation_name||'Shop workstation')}</strong><small>${esc(row.workstation_name||'Front Desk Workstation')}</small></div><div><span class="gc-trust-pill ${row.revoked_at?'revoked':''}">${row.revoked_at?'Revoked':'Trusted'}</span><small>${row.revoked_at?`Revoked ${esc(new Date(row.revoked_at).toLocaleString())}`:`Last active ${esc(new Date(row.last_seen_at).toLocaleString())}`}</small>${row.enrolled_by_name?`<small>Enrolled by ${esc(row.enrolled_by_name)}</small>`:''}</div>${row.revoked_at?'<span></span>':`<button type="button" class="text-button" data-revoke-workstation="${esc(row.id)}">Revoke</button>`}</div>`).join('');host.innerHTML=`<div class="card-title"><div><p class="eyebrow">Device trust</p><h2>Trusted shop workstations</h2><p>Shared computers are non-human identities. An owner or manager authorizes the browser with Discord; employees then identify themselves with their personal PIN.</p></div><button type="button" class="secondary-button" data-enroll-workstation>Enroll this browser</button></div><div class="gc-workstation-admin-list">${markup||'<p class="empty-state">No trusted shared workstations are enrolled yet.</p>'}</div>`;}
  async function load(){if(!eligible())return;try{rows=await rpc('list_trusted_workstations');render();}catch(error){console.warn('Trusted workstation list unavailable:',error?.message);}}
  document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;if(button.matches('[data-enroll-workstation]')){const loginButton=document.getElementById('workstation-enroll');if(!loginButton){window.GotCrackedDiagnostics?.error?.('Workstation enrollment control is unavailable.',{context:'Reload Portal and try again'});return;}loginButton.click();}if(button.matches('[data-revoke-workstation]')){button.disabled=true;try{await rpc('revoke_trusted_workstation',{target_id:button.dataset.revokeWorkstation,reason:'Revoked from Portal settings'});await load();}catch(error){window.GotCrackedDiagnostics?.error?.(error,{context:'Unable to revoke workstation'});button.disabled=false;}}});
  document.addEventListener('gc-view-changed',event=>{const view=typeof event.detail==='string'?event.detail:location.hash.slice(1);if(view==='settings')setTimeout(load,50);});
  style();load();window.GotCrackedWorkstationAdmin={version:'1.0.0',reload:load};
})();
