-- GotCracked Knowledge Base: major-brand repair source index
-- Each row contains original GotCracked technician guidance plus an outbound authoritative reference.
-- Manufacturer/source material is not copied into the Portal.

with seed(slug, device_category, manufacturer, model_family, title, source_type, source_name, source_url, source_license, tags) as (
  values
    ('kb-apple-iphone','Phone','Apple','iPhone','Apple iPhone - official repair reference','manufacturer','Apple Self Service Repair','https://support.apple.com/self-service-repair','External manufacturer reference; do not redistribute source content.',array['apple','iphone','repair manual','diagnostics']::text[]),
    ('kb-samsung-galaxy-phone','Phone','Samsung','Galaxy','Samsung Galaxy - official self-repair reference','manufacturer','Samsung Self-Repair','https://www.samsung.com/us/support/self-repair/','External manufacturer reference; do not redistribute source content.',array['samsung','galaxy','self repair','diagnostics']::text[]),
    ('kb-google-pixel-phone','Phone','Google','Pixel','Google Pixel - repair manuals and diagnostics','manufacturer','Google Pixel Repair','https://support.google.com/pixelphone/answer/14257407?hl=en','External manufacturer reference; do not redistribute source content.',array['google','pixel','repair diagnostics','manual']::text[]),
    ('kb-motorola-phone','Phone','Motorola','Moto / Edge / Razr','Motorola - Right to Repair reference','manufacturer','Motorola Right to Repair','https://en-us.support.motorola.com/app/right-to-repair/','External manufacturer reference; do not redistribute source content.',array['motorola','moto','edge','razr','schematic','service manual']::text[]),
    ('kb-xiaomi-phone','Phone','Xiaomi','Xiaomi / Redmi / POCO','Xiaomi / Redmi / POCO - self-repair reference','manufacturer','Xiaomi Self-Repair','https://www.mi.com/global/support/self-repair/','External manufacturer reference; availability varies by region.',array['xiaomi','redmi','poco','self repair']::text[]),
    ('kb-oneplus-phone','Phone','OnePlus','OnePlus','OnePlus - troubleshooting and service reference','manufacturer','OnePlus Support','https://www.oneplus.com/us/support/troubleshooting/details','External manufacturer reference; do not redistribute source content.',array['oneplus','oxygenos','troubleshooting']::text[]),
    ('kb-oppo-phone','Phone','OPPO','Find / Reno / A Series','OPPO - troubleshooting and repair-service reference','manufacturer','OPPO Support','https://support.oppo.com/en/','External manufacturer reference; do not redistribute source content.',array['oppo','find','reno','coloros']::text[]),
    ('kb-vivo-phone','Phone','vivo','X / V / Y Series','vivo - troubleshooting and service reference','manufacturer','vivo Support','https://www.vivo.com/en/support/','External manufacturer reference; do not redistribute source content.',array['vivo','phone','diagnostics','support']::text[]),
    ('kb-asus-phone','Phone','ASUS','Zenfone / ROG Phone','ASUS phone - self-replacement and diagnostics','manufacturer','ASUS Self Replacement','https://www.asus.com/us/support/faq/1051611/','External manufacturer reference; do not redistribute source content.',array['asus','zenfone','rog phone','smmi','self replacement']::text[]),
    ('kb-hmd-nokia-phone','Phone','HMD / Nokia','HMD / Nokia repairable models','HMD / Nokia - self-repair reference','manufacturer','HMD Self-Repair','https://www.hmd.com/en_int/self-repair/','HMD may direct supported models to partner guides; third-party content remains external.',array['hmd','nokia','self repair','phone']::text[]),
    ('kb-nothing-phone','Phone','Nothing','Nothing Phone / CMF Phone','Nothing / CMF - troubleshooting reference','manufacturer','Nothing Support','https://support.nothing.tech/hc/en-us/categories/7455115681041-Troubleshooting','External manufacturer troubleshooting reference.',array['nothing','cmf','phone','troubleshooting']::text[]),

    ('kb-apple-ipad','Tablet','Apple','iPad','Apple iPad - official repair reference','manufacturer','Apple Self Service Repair','https://support.apple.com/self-service-repair','External manufacturer reference; do not redistribute source content.',array['apple','ipad','repair manual']::text[]),
    ('kb-samsung-galaxy-tab','Tablet','Samsung','Galaxy Tab','Samsung Galaxy Tab - official self-repair reference','manufacturer','Samsung Self-Repair','https://www.samsung.com/us/support/self-repair/','External manufacturer reference; do not redistribute source content.',array['samsung','galaxy tab','tablet','self repair']::text[]),
    ('kb-google-pixel-tablet','Tablet','Google','Pixel Tablet','Google Pixel Tablet - repair diagnostics reference','manufacturer','Google Pixel Repair','https://support.google.com/pixelphone/answer/14257407?hl=en','External manufacturer reference; do not redistribute source content.',array['google','pixel tablet','repair diagnostics']::text[]),
    ('kb-microsoft-surface-tablet','Tablet','Microsoft','Surface Pro / Surface Go','Microsoft Surface Pro / Go - service guides','manufacturer','Microsoft Surface Service Guides','https://learn.microsoft.com/en-us/surface/service-guides/surface-service-guides','External manufacturer reference; do not redistribute source content.',array['microsoft','surface pro','surface go','service guide']::text[]),
    ('kb-lenovo-tablet','Tablet','Lenovo','Lenovo Tab','Lenovo tablet - support and service reference','manufacturer','Lenovo Support','https://support.lenovo.com/us/en/','External manufacturer reference; do not redistribute source content.',array['lenovo','tablet','manual','diagnostics']::text[]),
    ('kb-xiaomi-tablet','Tablet','Xiaomi','Xiaomi Pad','Xiaomi Pad - self-repair/support reference','manufacturer','Xiaomi Self-Repair','https://www.mi.com/global/support/self-repair/','External manufacturer reference; availability varies by region.',array['xiaomi','xiaomi pad','tablet','self repair']::text[]),
    ('kb-amazon-fire-tablet','Tablet','Amazon','Fire Tablet','Amazon Fire tablet - external teardown/repair index','external_reference','iFixit','https://www.ifixit.com/Device/Amazon_Fire','External-only. iFixit is CC BY-NC-SA 3.0; commercial ingestion requires permission/license.',array['amazon','fire tablet','ifixit','teardown']::text[]),

    ('kb-apple-macbook','Laptop','Apple','MacBook','Apple MacBook - official repair reference','manufacturer','Apple Self Service Repair','https://support.apple.com/self-service-repair','External manufacturer reference; do not redistribute source content.',array['apple','macbook','repair manual']::text[]),
    ('kb-microsoft-surface-laptop','Laptop','Microsoft','Surface Laptop / Laptop Studio','Microsoft Surface Laptop - service guides','manufacturer','Microsoft Surface Service Guides','https://learn.microsoft.com/en-us/surface/service-guides/surface-service-guides','External manufacturer reference; do not redistribute source content.',array['microsoft','surface laptop','service guide','diagnostics']::text[]),
    ('kb-dell-laptop','Laptop','Dell','Inspiron / XPS / Latitude / Precision / Alienware','Dell laptop - service manuals and diagnostics','manufacturer','Dell Self-Repair','https://www.dell.com/support/contents/en-us/article/warranty/self-repair','External manufacturer reference; do not redistribute source content.',array['dell','xps','latitude','alienware','service manual']::text[]),
    ('kb-hp-laptop','Laptop','HP','Pavilion / Envy / Spectre / EliteBook / ProBook / Omen','HP laptop - Maintenance and Service Guides','manufacturer','HP Support','https://support.hp.com/us-en/','External manufacturer reference; do not redistribute source content.',array['hp','laptop','maintenance service guide','diagnostics']::text[]),
    ('kb-lenovo-laptop','Laptop','Lenovo','ThinkPad / IdeaPad / Yoga / Legion','Lenovo laptop - hardware maintenance reference','manufacturer','Lenovo Support','https://support.lenovo.com/us/en/','External manufacturer reference; do not redistribute source content.',array['lenovo','thinkpad','ideapad','yoga','legion']::text[]),
    ('kb-asus-laptop','Laptop','ASUS','Zenbook / Vivobook / ROG / TUF','ASUS laptop - self-replacement and diagnostics','manufacturer','ASUS Self Replacement','https://www.asus.com/us/support/faq/1051611/','External manufacturer reference; do not redistribute source content.',array['asus','zenbook','vivobook','rog','tuf','myasus']::text[]),
    ('kb-acer-laptop','Laptop','Acer','Aspire / Swift / Nitro / Predator / TravelMate','Acer laptop - manuals and support reference','manufacturer','Acer Support','https://www.acer.com/us-en/support','External manufacturer reference; do not redistribute source content.',array['acer','aspire','swift','nitro','predator']::text[]),
    ('kb-msi-laptop','Laptop','MSI','MSI Laptop','MSI laptop - support and diagnostic reference','manufacturer','MSI Support','https://www.msi.com/support','External manufacturer reference; do not redistribute source content.',array['msi','laptop','gaming','diagnostics']::text[]),
    ('kb-framework-laptop','Laptop','Framework','Framework Laptop','Framework laptop - official repair and upgrade guides','manufacturer','Framework Support','https://frame.work/support','External manufacturer reference; do not redistribute source content.',array['framework','laptop','repair guide','mainboard']::text[]),
    ('kb-samsung-galaxy-book','Laptop','Samsung','Galaxy Book','Samsung Galaxy Book - self-repair reference','manufacturer','Samsung Self-Repair','https://www.samsung.com/us/support/self-repair/','External manufacturer reference; do not redistribute source content.',array['samsung','galaxy book','laptop','self repair']::text[]),
    ('kb-chromebook','Laptop','Google / OEM','Chromebook','Chromebook - ChromeOS troubleshooting and recovery','manufacturer','Google Chromebook Help','https://support.google.com/chromebook/?hl=en','External platform-manufacturer reference; individual hardware service guides remain OEM-specific.',array['chromebook','chromeos','recovery','diagnostics']::text[]),

    ('kb-apple-mac-desktop','Desktop','Apple','Mac mini / Mac Studio / iMac / Mac Pro','Apple Mac desktop - official repair reference','manufacturer','Apple Self Service Repair','https://support.apple.com/self-service-repair','External manufacturer reference; do not redistribute source content.',array['apple','mac mini','mac studio','imac','desktop']::text[]),
    ('kb-dell-desktop','Desktop','Dell','OptiPlex / Precision / XPS / Alienware','Dell desktop - service manuals and diagnostics','manufacturer','Dell Self-Repair','https://www.dell.com/support/contents/en-us/article/warranty/self-repair','External manufacturer reference; do not redistribute source content.',array['dell','desktop','optiplex','alienware','service manual']::text[]),
    ('kb-hp-desktop','Desktop','HP','HP / Pavilion / Omen / Z Workstation','HP desktop - Maintenance and Service Guides','manufacturer','HP Support','https://support.hp.com/us-en/','External manufacturer reference; do not redistribute source content.',array['hp','desktop','omen','workstation','service guide']::text[]),
    ('kb-lenovo-desktop','Desktop','Lenovo','ThinkCentre / Legion / ThinkStation','Lenovo desktop - hardware maintenance reference','manufacturer','Lenovo Support','https://support.lenovo.com/us/en/','External manufacturer reference; do not redistribute source content.',array['lenovo','desktop','thinkcentre','legion','thinkstation']::text[]),
    ('kb-asus-desktop','Desktop','ASUS','ROG / ExpertCenter / Mini PC','ASUS desktop - self-replacement and diagnostics','manufacturer','ASUS Self Replacement','https://www.asus.com/us/support/faq/1051611/','External manufacturer reference; do not redistribute source content.',array['asus','desktop','rog','mini pc','myasus']::text[]),
    ('kb-acer-desktop','Desktop','Acer','Aspire / Predator / Veriton','Acer desktop - manuals and support reference','manufacturer','Acer Support','https://www.acer.com/us-en/support','External manufacturer reference; do not redistribute source content.',array['acer','desktop','predator','veriton']::text[]),
    ('kb-msi-desktop','Desktop','MSI','MSI Desktop','MSI desktop - support and troubleshooting reference','manufacturer','MSI Support','https://www.msi.com/support','External manufacturer reference; do not redistribute source content.',array['msi','desktop','gaming','troubleshooting']::text[]),

    ('kb-playstation','Console','Sony','PlayStation 4 / PlayStation 5','PlayStation - official troubleshooting and repair reference','manufacturer','PlayStation Support','https://www.playstation.com/en-us/support/','External manufacturer reference; do not redistribute source content.',array['sony','playstation','ps4','ps5','safe mode']::text[]),
    ('kb-xbox','Console','Microsoft','Xbox One / Series X / Series S','Xbox - official troubleshooting reference','manufacturer','Xbox Support','https://support.xbox.com/en-US/','External manufacturer troubleshooting reference; detailed board repair may require separate licensed/reference sources.',array['microsoft','xbox','series x','series s','controller']::text[]),
    ('kb-nintendo-switch','Console','Nintendo','Switch / Switch OLED / Switch Lite / Switch 2','Nintendo Switch family - official troubleshooting reference','manufacturer','Nintendo Support','https://en-americas-support.nintendo.com/','External manufacturer troubleshooting reference; detailed board repair may require separate licensed/reference sources.',array['nintendo','switch','switch 2','joy-con','dock']::text[]),
    ('kb-steam-deck','Console','Valve','Steam Deck LCD / OLED','Steam Deck - Valve support and repair-guide gateway','manufacturer','Valve Steam Support','https://help.steampowered.com/en/wizard/HelpWithSteamDeck','Valve links to iFixit for parts/guides; iFixit content remains external until commercially licensed.',array['valve','steam deck','oled','handheld','ifixit']::text[]),
    ('kb-rog-ally','Console','ASUS','ROG Ally / Ally X','ASUS ROG Ally - service-manual reference','manufacturer','ASUS Self Replacement','https://www.asus.com/us/supportonly/rog%20ally%20%282023%29/helpdesk_service_guide/','External manufacturer reference; do not redistribute source content.',array['asus','rog ally','ally x','handheld','service manual']::text[]),
    ('kb-legion-go','Console','Lenovo','Legion Go','Lenovo Legion Go - support and service reference','manufacturer','Lenovo Support','https://support.lenovo.com/us/en/','External manufacturer reference; do not redistribute source content.',array['lenovo','legion go','handheld','windows']::text[])
), expanded as (
  select s.*,
    'GotCracked technician index entry for ' || s.manufacturer || ' ' || s.model_family || '. Use the linked authoritative source for the exact model, revision, disassembly sequence, diagnostics, safety notices, compatible parts, firmware, and post-repair requirements. This Portal entry is original summary metadata, not a copy of the source guide.' as summary,
    case s.device_category
      when 'Phone' then jsonb_build_array('Identify the exact model, regional variant, storage or board revision, software version, and customer symptom.','Run supported OEM diagnostics and non-destructive software checks before opening the phone.','Open the linked source and exact model documentation before disassembly; confirm battery, adhesive, calibration, pairing, and part-compatibility requirements.','After repair verify display/touch, charging/battery, cameras, audio, biometrics, wireless, sensors, thermals, and post-repair calibration where applicable.')
      when 'Tablet' then jsonb_build_array('Identify the exact tablet model, generation, regional or cellular variant, and complaint.','Run supported OEM diagnostics and document display/touch, battery/charge, cameras, audio, wireless, and software behavior.','Use the linked exact-model service or repair source before opening; confirm adhesive, battery, frame, calibration, and part requirements.','After repair verify touch across the full panel, charging, battery, cameras, audio, wireless, sensors, sleep/wake, and software health.')
      when 'Laptop' then jsonb_build_array('Identify the exact model, machine/service tag, board revision, BIOS/firmware, and complaint.','Run OEM preboot or OS diagnostics where available and record power, battery, display, keyboard, trackpad, ports, storage, memory, wireless, fan, and thermal results.','Use the exact service guide before opening; confirm battery disconnect, screw map, cable routing, thermal materials, parts, and firmware procedures.','After repair rerun diagnostics plus boot, charging, display, input, ports, storage, memory, wireless, audio, camera, fan, thermal, sleep/wake, and sustained-load tests.')
      when 'Desktop' then jsonb_build_array('Identify the exact model, service tag or serial, motherboard or chassis revision, firmware, configuration, and complaint.','Run OEM diagnostics where available and document POST codes, power, memory, CPU, GPU, storage, ports, networking, audio, and thermal behavior.','Use the exact service manual before internal work; confirm power isolation, PSU hazards, cable routing, parts compatibility, BIOS requirements, and thermal materials.','After repair verify POST, firmware, memory, storage, GPU, network, ports, audio, fan control, thermals, and sustained-load stability.')
      else jsonb_build_array('Identify the exact console or handheld model, hardware revision, firmware, accessories, and complaint.','Run manufacturer-supported troubleshooting before disassembly and document power, boot, video, network, controls, storage, audio, charging, and thermal behavior as applicable.','Use the linked source plus an exact-model licensed or authoritative teardown when board-level or internal repair detail is required.','After repair verify cold boot, updates, video, network, storage, controls, ports, audio, charging or power, thermals, and repeated-load stability.')
    end as diagnostic_steps
  from seed s
)
insert into public.repair_guides (
  slug, device_category, manufacturer, model_family, symptom, title, summary,
  diagnostic_steps, likely_causes, tools_notes, parts_notes, cautions, tags,
  difficulty, bench_time_minutes, active, source_type, source_name, source_url,
  source_license, verified_at, verification_notes, procedure_version
)
select
  e.slug, e.device_category, e.manufacturer, e.model_family,
  'Model-specific repair, teardown, diagnostic, troubleshooting, parts, firmware, or post-repair reference needed',
  e.title, e.summary, e.diagnostic_steps,
  case e.device_category
    when 'Phone' then jsonb_build_array('Display or touch assembly','Battery or charging path','Camera, audio, sensor, or flex','Software or calibration','Board-level fault')
    when 'Tablet' then jsonb_build_array('Display or digitizer','Battery or charging path','Port or modular component','Software or storage','Board-level fault')
    when 'Laptop' then jsonb_build_array('Battery or power input','Display or input module','Memory or storage','Thermal or fan system','Motherboard or firmware')
    when 'Desktop' then jsonb_build_array('PSU or power delivery','Memory, CPU, or motherboard','GPU or video path','Storage or firmware','Thermal or peripheral fault')
    else jsonb_build_array('Power or charging system','HDMI, display, or dock path','Storage or system software','Controller or mechanical module','Board-level fault') end,
  'Use the linked manufacturer/source documentation, ESD-safe tools, and model-appropriate diagnostics. For board work, use only legally usable exact-revision schematic/reference material.',
  'Verify exact model/revision and part compatibility before ordering or installation. Check pairing, calibration, serialization, firmware, and post-repair tool requirements.',
  case when e.device_category='Desktop' then 'Disconnect AC power and observe PSU/mains-voltage safety. Stop if liquid, burnt components, or unsafe power conditions are present.' else 'Stop for swollen or damaged lithium batteries, active liquid, smoke, abnormal heat, or severe structural damage. Follow the exact source safety guidance.' end,
  e.tags, 'Reference', 30, true, e.source_type, e.source_name, e.source_url, e.source_license, now(),
  'Source catalog verified for GotCracked Knowledge Base indexing on 2026-08-27; linked source remains authoritative and should be rechecked for the exact model before service.', 1
from expanded e
where not exists (
  select 1 from public.repair_guides g
  where g.location_id is null and g.slug=e.slug
);
